"""add timezone field to DBUser

Revision ID: 02e1168c6da3
Revises: 0da47370d51d
Create Date: 2024-09-27 11:50:04.934914

"""

from typing import Optional, Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "02e1168c6da3"
down_revision: Optional[str] = "0da47370d51d"
branch_labels: Optional[Sequence[str]] = None
depends_on: Optional[Sequence[str]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("timezone", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "timezone")
    # ### end Alembic commands ###
