"""Add RepeatType enum to reminders

Revision ID: 25ab781aab0f
Revises: ce68288644fc
Create Date: 2024-10-01 12:22:33.025925

"""

from typing import Optional, Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25ab781aab0f"
down_revision: Optional[str] = "ce68288644fc"
branch_labels: Optional[Sequence[str]] = None
depends_on: Optional[Sequence[str]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Операция, которая вручную добавляет новое значение в тип Enum
    op.execute("ALTER TYPE repeattype ADD VALUE 'month'")
    # ### end Alembic commands ###


def downgrade() -> None: ...
