"""add timezone field to DBUser_3

Revision ID: ce68288644fc
Revises: 02e1168c6da3
Create Date: 2024-09-27 12:06:02.005985

"""

from typing import Optional, Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce68288644fc"
down_revision: Optional[str] = "02e1168c6da3"
branch_labels: Optional[Sequence[str]] = None
depends_on: Optional[Sequence[str]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("utc_offset", sa.Integer(), nullable=True))
    op.drop_column("users", "timezone")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("timezone", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("users", "utc_offset")
    # ### end Alembic commands ###
